services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: search-benchmark
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@paradedb:5432/testing
    depends_on:
      - redis
      - dragonfly_old
      - dragonfly_new
      - paradedb
      - meilisearch
      - typesense
      - elasticsearch

  dragonfly_old:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.31.2
  
  dragonfly_new:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.32.0
  
  redis:
    image: redis:8.0-bookworm

  meilisearch:
    image: getmeili/meilisearch:v1.15
    environment:
      - MEILI_MASTER_KEY=testing

  typesense:
    image: typesense/typesense:29.0
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=testing'

  paradedb:
    image: paradedb/paradedb:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testing

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:9
    volumes:
      - 'elasticsearch-data:/bitnami/elasticsearch/data'

volumes:
  typesense-data:
  elasticsearch-data: